### ISSUE TITLE
Black screen on LG web OS browser 

### ISSUE THREAD

**Issue by roshank231** [mateussouzaweb/crunchyroll-webos#4]
Not working on my LG web is tv browser.

all im getting when I go to the link is a black screen with a grey panel on the left. Any help?

**Comment by mateussouzaweb** [comment]
I need a few more details to investigate. Please send me these details below:

- What is your TV model?
- What is your WebOS version?

**Comment by roshank231** [comment]
Hi ,

the tv model is UJ635V and the software version is 06.00.15. If there’s anything else that will help let me know.

**Comment by MarcoFaul** [comment]
Same problem with my LG TV 50UH635V and software version: 05.50.95

**Comment by mateussouzaweb** [comment]
@MarcoFaul @roshank231 I just released a new version of the app, can you please check if that works for you now? I do believe that was a caching issue, but if the problem persists, we investigate further.

**Comment by roshank231** [comment]
Unfortunately I still can’t acesss the app through web browser on the Smart TV.

**Comment by mateussouzaweb** [comment]
@roshank231 I was able to reproduce the problem with TV emulator e the issue has been fixed with the recent commits. Can you please try again? My TV is on version 05.00.15 and works fine...

**Comment by roshank231** [comment]
Hi the issue still persists for me but I found by using a similar service on mobile and casting through another LG app I can watch Crunchyroll pretty easily on my LG tv, so don’t stress yourself over this.

Thanks for trying though!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Bebooo43** [comment]
I have the same problem with my LG TV WebOS v5.20.10
I got a black screen with an empty grey bar on left

I've followed your comment [here](https://github.com/mateussouzaweb/crunchyroll-webos/issues/7#issuecomment-846563260)  to make the ipk using [compactor](https://github.com/mateussouzaweb/compactor) 
and i got `com.crunchyroll.webos_1.4.0_all.ipk` in the bin folder.

**Comment by Bebooo43** [comment]
The only version that works on my TV is `v1.0.0` ipk that was provided before on bin path

**Comment by mateussouzaweb** [comment]
@Bebooo43 see if that app build works for you: https://drive.google.com/file/d/17NSWmhWLNvupp8WMJrYi8jPSym42moFw/view?usp=sharing

**Comment by Bebooo43** [comment]
@mateussouzaweb Your build works ^_^
I'm not sure what I did wrong. I make the build under Ubuntu 20.04 and following the steps but it didn't work :D

**Comment by Bebooo43** [comment]
@mateussouzaweb I found the problem with my build, I've used the prebuilt compactor v0.0.2
the latest version is 0.0.3 After compiling and using it. it worked correctly on my TV
Many thanks @mateussouzaweb
